# Generated by Django 4.2.5 on 2023-10-06 17:33

from django.db import migrations

def insert_offences_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    sql = """
    INSERT INTO offences_offence (offence_id, offence_description, offence_max_fine, offence_max_points) VALUES
    (1, 'Speeding', 1000, 3),
    (2, 'Speeding on a motorway', 2500, 6),
    (3, 'Seat belt offence', 500, 0),
    (4, 'Illegal parking', 500, 0),
    (5, 'Drink driving', 10000, 11),
    (6, 'Driving without a licence', 10000, 0),
    (7, 'Driving without a licence', 10000, 0),
    (8, 'Traffic light offences', 1000, 3),
    (9, 'Cycling on pavement', 500, 0),
    (10, 'Failure to have control of vehicle', 1000, 3),
    (11, 'Dangerous driving', 1000, 11),
    (12, 'Careless driving', 5000, 6),
    (13, 'Dangerous cycling', 2500, 0);    
    """
    migrations.RunSQL(sql, reverse_sql=migrations.RunSQL.noop)

class Migration(migrations.Migration):

    dependencies = [
        ('offences', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(insert_offences_data)
    ]


# THIS DID NOT WORK ON FIRST RUN, FOR THIS REASON USE SECOND TRY: 005_add_offences_data_new