# Generated by Django 4.2.4 on 2023-10-07 16:52

from django.db import migrations

def insert_incidents_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Incident = apps.get_model('reports', 'Incident')
    
    incidents_data = [
        {'id': 1, 'vehicle_id': 4, 'person_id': 4, 'incident_date': '2017-12-01', 'incident_description': '40mph in a 30 limit', 'offence_id': 1},
        {'id': 2, 'vehicle_id': 8, 'person_id': 8, 'incident_date': '2017-11-01', 'incident_description': 'Double parked', 'offence_id': 4},
        {'id': 3, 'vehicle_id': 2, 'person_id': 4, 'incident_date': '2017-09-17', 'incident_description': '110mph on motorway', 'offence_id': 1},
        {'id': 4, 'vehicle_id': 3, 'person_id': 2, 'incident_date': '2017-08-22', 'incident_description': 'Failure to stop at a red light - travelling 25mph', 'offence_id': 8},
        {'id': 5, 'vehicle_id': 2, 'person_id': 4, 'incident_date': '2017-10-17', 'incident_description': 'Not wearing a seatbelt on the M1', 'offence_id': 3},
    ]

    for data in incidents_data:
        Incident.objects.using(db_alias).create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_incidents_data, migrations.RunPython.noop),
    ]
