# Generated by Django 4.2.4 on 2023-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address1',
            field=models.CharField(default='Not Recorded', max_length=1024, verbose_name='Address Line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='address2',
            field=models.CharField(default='Not Recorded', max_length=1024, verbose_name='Address Line 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='Not Recorded', max_length=1024, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='post_code',
            field=models.CharField(default='Not Recorded', max_length=7, verbose_name='Postal Code'),
            preserve_default=False,
        ),
    ]
