# Generated by Django 4.2.4 on 2023-09-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_address1_person_address2_person_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address2',
        ),
    ]
