# Generated by Django 4.2.4 on 2023-10-07 17:13

from django.db import migrations, models

def insert_people_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Person = apps.get_model('people', 'Person')
    
    people_data = [
        # {'id': 1, 'first_name': 'James', 'last_name': 'Smith', 'address1': '23 Barnsdale Road', 'city': 'Leicester', 'post_code': , 'driving_licence_number': 'SMITH92LDOFJJ829'},
        # {'id': 2, 'first_name': 'Jennifer', 'last_name': 'Allen', 'address1': '46 Bramcote Drive', 'city': 'Nottingham', 'post_code': , 'driving_licence_number': 'ALLEN88K23KLR9B3'},
        {'id': 3, 'first_name': 'John', 'last_name': 'Myers', 'address1': '323 Derby Road', 'city': 'Nottingham', 'post_code': 'NG7 2DZ', 'driving_licence_number': 'MYERS99JDW8REWL3'},
        {'id': 4, 'first_name': 'James', 'last_name': 'Smith', 'address1': '26 Devonshire Avenue', 'city': 'Nottingham', 'post_code': 'NG9 1BS', 'driving_licence_number': 'SMITHR004JFS20TR'},
        {'id': 5, 'first_name': 'Terry', 'last_name': 'Brown', 'address1': '7 Clarke Rd', 'city': 'Nottingham', 'post_code': 'NG2 3JJ', 'driving_licence_number': 'BROWND3PJJ39DLFG'},
        {'id': 6, 'first_name': 'Mary', 'last_name': 'Adams', 'address1': '38 Thurman St', 'city': 'Nottingham', 'post_code': 'NG7 5AU', 'driving_licence_number': 'ADAMSH9O3JRHH107'},
        {'id': 7, 'first_name': 'Neil', 'last_name': 'Becker', 'address1': '6 Fairfax Close', 'city': 'Nottingham', 'post_code': 'NG5 1JH', 'driving_licence_number': 'BECKE88UPR840F9R'},
        {'id': 8, 'first_name': 'Angela', 'last_name': 'Smith', 'address1': '30 Avenue Road', 'city': 'Grantham', 'post_code': 'NG31 6TH', 'driving_licence_number': 'SMITH222LE9FJ5DS'},
        {'id': 9, 'first_name': 'Xene', 'last_name': 'Medora', 'address1': '3 Rushworth Ave', 'city': 'Nottingham', 'post_code': 'NG2 7LF', 'driving_licence_number': 'MEDORH914ANBB223'}
    ]

    for data in people_data:
        Person.objects.using(db_alias).create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_person_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='post_code',
            field=models.CharField(verbose_name='Postal Code', max_length=8),
        ),

        migrations.RunPython(insert_people_data, migrations.RunPython.noop),
    ]
