# Generated by Django 4.2.4 on 2023-09-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=7)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=255)),
            ],
        ),
    ]
