# Generated by Django 4.2.4 on 2023-10-07 17:13

from django.db import migrations

def insert_vehicles_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Vehicle = apps.get_model('vehicles', 'Vehicle')
    
    vehicle_data = [
        {'id': 1, 'registration': 'LB15AJL', 'make': 'Ford', 'model': 'Fiesta', 'colour': 'Blue'},
        {'id': 2, 'registration': 'MY64PRE', 'make': 'Ferrari', 'model': '458', 'colour': 'Red'},
        {'id': 3, 'registration': 'FD65WPQ', 'make': 'Vauxhall', 'model': 'Astra', 'colour': 'Silver'},
        {'id': 4, 'registration': 'FJ17AUG', 'make': 'Honda', 'model': 'Civic', 'colour': 'Green'},
        {'id': 5, 'registration': 'FP16KKE', 'make': 'Toyota', 'model': 'Prius', 'colour': 'Silver'},
        {'id': 6, 'registration': 'FP66KLM', 'make': 'Ford', 'model': 'Mondeo', 'colour': 'Black'},
        {'id': 7, 'registration': 'DJ14SLE', 'make': 'Ford', 'model': 'Focus', 'colour': 'White'},
        {'id': 8, 'registration': 'NY64KWD', 'make': 'Nissan', 'model': 'Pulsar', 'colour': 'Red'},
        {'id': 9, 'registration': 'BC16OEA', 'make': 'Renault', 'model': 'Scenic', 'colour': 'Silver'},
        {'id': 10, 'registration': 'AD223NG', 'make': 'Hyundai', 'model': 'i30', 'colour': 'Grey'},
    ]

    for data in vehicle_data:
        Vehicle.objects.using(db_alias).create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_vehicles_data, migrations.RunPython.noop),
    ]
